// Generated by scripts/register-characters.ts.
import { Component, type GeaElement } from '@geastack/core'
import type { CharacterId } from './registry.js'
import Kitt from './kitt/View.js'
import './kitt/styles.css'
import Echo from './echo/View.js'
import './echo/styles.css'
import Flora from './flora/View.js'
import './flora/styles.css'
import Nova from './nova/View.js'
import './nova/styles.css'

interface CharacterViewProps {
  id: CharacterId
}
export default class CharacterView extends Component<GeaElement, CharacterViewProps> {
  template({ id }: CharacterViewProps): JSX.Element {
    return (
      <div class={`character-view theme-${id}`}>
        {id === 'kitt' && <Kitt />}
        {id === 'echo' && <Echo />}
        {id === 'flora' && <Flora />}
        {id === 'nova' && <Nova />}
      </div>
    )
  }
}
