// Generated by scripts/register-characters.ts.
import type { CharacterId } from './registry.js'
import { prime as primeKitt, paint as paintKitt } from './kitt/animation.js'
import { prime as primeEcho, paint as paintEcho } from './echo/animation.js'
import { prime as primeFlora, paint as paintFlora } from './flora/animation.js'
import { prime as primeNova, paint as paintNova } from './nova/animation.js'

let primed = false

export function paintCharacters(
  elapsed: number,
  level: number,
  id: CharacterId,
  advance: boolean,
): void {
  if (!primed) {
    // Evaluate every primer, even if an earlier character is not mounted yet.
    const readyKitt = primeKitt()
    const readyEcho = primeEcho()
    const readyFlora = primeFlora()
    const readyNova = primeNova()

    primed = readyKitt && readyEcho && readyFlora && readyNova
  }

  if (!advance) {
    return
  }

  if (id === 'kitt') {
    paintKitt(elapsed, level, true)
  } else if (id === 'echo') {
    paintEcho(elapsed, level, true)
  } else if (id === 'flora') {
    paintFlora(elapsed, level, true)
  } else if (id === 'nova') {
    paintNova(elapsed, level, true)
  }
}
