// Generated by scripts/register-characters.ts.
import kitt from './kitt/character.ts'
import echo from './echo/character.ts'
import flora from './flora/character.ts'
import nova from './nova/character.ts'

export type CharacterId = 'kitt' | 'echo' | 'flora' | 'nova'
export const characterIds: CharacterId[] = ['kitt', 'echo', 'flora', 'nova']
export const characters = [kitt, echo, flora, nova]
